In [239]:
from pathlib import Path
import json
import pandas as pd

In [240]:
DATA_DIR = Path("../Datasets")

json_files = sorted(DATA_DIR.glob("*.json"))

print(f"Total JSON files: {len(json_files)}")
print("First file:", json_files[0].name)

Total JSON files: 742
First file: 90044961.json

In [241]:
sample_file = json_files[0]

with open(sample_file, "r", encoding="utf-8") as f:
    first_data = json.load(f)

print("Loaded:", sample_file.name)

Loaded: 90044961.json

In [242]:
for key, value in first_data.items():
    print(f"{key}: {type(value).__name__}")

configuration: dict
description: str
id: str
info: dict
module_version: str
name: str
rewards: list
schema_version: int
specification: dict
statuses: list
steps: list
title: str
version: str

In [243]:
for key in ["configuration", "info", "rewards", "statuses", "steps"]:
    value = first_data[key]

    print(f"\n--- {key} ---")
    print("Type:", type(value).__name__)

    if isinstance(value, dict):
        print("Keys:", value.keys())

    elif isinstance(value, list):
        print("Length:", len(value))

        if value:
            print("First item type:", type(value[0]).__name__)

--- configuration ---
Type: dict
Keys: dict_keys(['actTimeout', 'boardSize', 'episodeSteps', 'farmHandCostMult', 'marketParams', 'maxMarketOrdersPerTurn', 'runTimeout', 'seed', 'shedCapacity', 'startingMoney', 'townCenterSellInterval', 'townShopSellInterval', 'townShopUnlockInterval', 'turnsPerDay', 'weedSpawnChance'])

--- info ---
Type: dict
Keys: dict_keys(['Agents', 'EpisodeId', 'LiveVideoPath', 'TeamNames', 'seed'])

--- rewards ---
Type: list
Length: 2
First item type: float

--- statuses ---
Type: list
Length: 2
First item type: str

--- steps ---
Type: list
Length: 720
First item type: list

In [244]:
step = first_data["steps"][0]

print("Step type:", type(step).__name__)
print("Number of players:", len(step))

for player, agent in enumerate(step):
    print(f"\nPlayer {player}")
    print("Keys:", agent.keys())

Step type: list
Number of players: 2

Player 0
Keys: dict_keys(['action', 'info', 'observation', 'reward', 'status'])

Player 1
Keys: dict_keys(['action', 'info', 'observation', 'reward', 'status'])

In [245]:
agent = first_data["steps"][0][0]

print("Action:")
print(agent["action"])

print("\nReward:")
print(agent["reward"])

print("\nStatus:")
print(agent["status"])

print("\nObservation keys:")
print(agent["observation"].keys())

Action:
{'farmer': ['PASS'], 'hands': [], 'market': []}

Reward:
0

Status:
ACTIVE

Observation keys:
dict_keys(['day', 'farms', 'hour', 'market', 'player', 'private', 'remainingOverageTime', 'step', 'town'])

In [246]:
obs = agent["observation"]

for key, value in obs.items():
    print(f"{key}: {type(value).__name__}")

day: int
farms: list
hour: int
market: dict
player: int
private: dict
remainingOverageTime: int
step: int
town: dict

In [247]:
player = 0

farm = (
    first_data["steps"][0][player]
    ["observation"]["farms"][player]
)

for key, value in farm.items():
    print(f"{key}: {type(value).__name__}")

farmer: list
hands: list
hires_today: int
money: float
tiles: list
unlocked_quadrants: list

In [248]:
step_number = 100
player = 0

money = first_data["steps"][step_number][player]["observation"]["farms"][player]["money"]

print(money)

829.0

In [249]:
prices = (
    first_data["steps"][0][0]
    ["observation"]["market"]["prices"]
)

print(prices)

{'CARROT': 35, 'EGG': 50, 'FERTILIZER': 100, 'MELON': 250, 'MILK': 160, 'STRAWBERRY': 120, 'TOMATO': 60, 'WHEAT': 25, 'WOOL': 200}

In [250]:
step_number = 100
player = 0

carrot_price = (
    first_data["steps"][step_number][player]
    ["observation"]["market"]["prices"]["CARROT"]
)

print(carrot_price)

38

In [251]:
private = (
    first_data["steps"][0][0]
    ["observation"]["private"]
)

print("SEEDS")
print(private["seeds"])

print("\nSHED")
print(private["shed"])

SEEDS
{'CARROT': 0, 'MELON': 0, 'STRAWBERRY': 0, 'TOMATO': 0, 'WHEAT': 0}

SHED
{'CARROT': 0, 'COW': 0, 'EGG': 0, 'FERTILIZER': 0, 'GOOSE': 0, 'MELON': 0, 'MILK': 0, 'SHEEP': 0, 'STRAWBERRY': 0, 'TOMATO': 0, 'WHEAT': 0, 'WOOL': 0}

In [252]:
for step_number in [0, 100, 300, 719]:

    agent = first_data["steps"][step_number][0]
    farm = agent["observation"]["farms"][0]

    print(f"\n===== STEP {step_number} =====")
    print("Money:", farm["money"])
    print("Farmer:", farm["farmer"])

===== STEP 0 =====
Money: 3000.0
Farmer: [4, 4]

===== STEP 100 =====
Money: 829.0
Farmer: [4, 4]

===== STEP 300 =====
Money: 10987.0
Farmer: [2, 4]

===== STEP 719 =====
Money: 151880.0
Farmer: [5, 4]

In [253]:
unique_tile_examples = {}

for step_data in first_data["steps"]:
    for player, agent in enumerate(step_data):

        farm = agent["observation"]["farms"][player]

        for row in farm["tiles"]:
            for tile in row:

                if isinstance(tile, dict):

                    tile_type = tile.get("kind", "UNKNOWN")

                    if tile_type not in unique_tile_examples:
                        unique_tile_examples[tile_type] = tile


for tile_type, example in unique_tile_examples.items():

    print(f"\n--- {tile_type} ---")
    print("Example:", example)
    print("Keys:", example.keys())

--- PASTURE ---
Example: {'kind': 'PASTURE'}
Keys: dict_keys(['kind'])

--- PLANT ---
Example: {'consecutive_unwatered': 1, 'crop': 'MELON', 'fertilized_until_day': -1, 'kind': 'PLANT', 'max_lifespan_step': 312, 'planted_day': 0, 'watered_today': False, 'yield_units': 1}
Keys: dict_keys(['consecutive_unwatered', 'crop', 'fertilized_until_day', 'kind', 'max_lifespan_step', 'planted_day', 'watered_today', 'yield_units'])

--- WEED ---
Example: {'kind': 'WEED'}
Keys: dict_keys(['kind'])

In [254]:
import sys
import importlib

sys.path.append("..")

import src.features.extractor as extractor

importlib.reload(extractor)

extract_episode = extractor.extract_episode

rows = extract_episode(first_data)

In [255]:
episode_df = pd.DataFrame(rows)

In [256]:
print("Shape:", episode_df.shape)
print("Total features:", len(episode_df.columns))

Shape: (1440, 64)
Total features: 64

In [257]:
missing = episode_df.isnull().sum()

print("Missing values:")
print(missing[missing > 0])

Missing values:
Series([], dtype: int64)

In [258]:
print("Duplicate rows:", episode_df.duplicated().sum())

Duplicate rows: 0

In [259]:
print(episode_df.dtypes)

episode_id                  str
player                    int64
step                      int64
day                       int64
hour                      int64
                          ...
fertilized_plant_count    int64
fed_animal_count          int64
unfed_animal_count        int64
cared_animal_count        int64
uncared_animal_count      int64
Length: 64, dtype: object

In [260]:
episode_df[
    [
        "episode_id",
        "player",
        "step",
        "day",
        "hour",
        "money",
        "step_reward",
        "final_reward",
        "carrot_price",
        "carrot_seed",
        "shed_carrot"
    ]
].head(10)

,episode_id,player,step,day,hour,money,step_reward,final_reward,carrot_price,carrot_seed,shed_carrot
0,c6bc5296-9060-11f1-814b-0242ac130202,0,0,0,0,3000.0,0.0,151880.0,35,0,0
1,c6bc5296-9060-11f1-814b-0242ac130202,1,0,0,0,3000.0,0.0,152469.0,35,0,0
2,c6bc5296-9060-11f1-814b-0242ac130202,0,1,0,1,2058.0,0.0,151880.0,36,0,0
3,c6bc5296-9060-11f1-814b-0242ac130202,1,1,0,1,2058.0,0.0,152469.0,36,0,0
4,c6bc5296-9060-11f1-814b-0242ac130202,0,2,0,2,1442.0,0.0,151880.0,36,0,0
5,c6bc5296-9060-11f1-814b-0242ac130202,1,2,0,2,1442.0,0.0,152469.0,36,0,0
6,c6bc5296-9060-11f1-814b-0242ac130202,0,3,0,3,984.0,0.0,151880.0,36,0,0
7,c6bc5296-9060-11f1-814b-0242ac130202,1,3,0,3,984.0,0.0,152469.0,36,0,0
8,c6bc5296-9060-11f1-814b-0242ac130202,0,4,0,4,426.0,0.0,151880.0,36,0,0
9,c6bc5296-9060-11f1-814b-0242ac130202,1,4,0,4,426.0,0.0,152469.0,36,0,0

In [261]:
import importlib
import src.data.batch_processor as batch_processor

importlib.reload(batch_processor)

process_batch = batch_processor.process_batch

In [262]:
test_df = process_batch(
    json_files,
    max_files=5
)

print("\nFinal shape:", test_df.shape)
print("Total features:", len(test_df.columns))

Processing 1/5: 90044961.json
  ✓ Rows: 1440 | Columns: 64
Processing 2/5: 90045719.json
  ✓ Rows: 1440 | Columns: 64
Processing 3/5: 90047087.json
  ✓ Rows: 1440 | Columns: 64
Processing 4/5: 90047777.json
  ✓ Rows: 1440 | Columns: 64
Processing 5/5: 90048477.json
  ✓ Rows: 1440 | Columns: 64

Final shape: (7200, 64)
Total features: 64

In [263]:
from pathlib import Path
import importlib

import src.data.batch_processor as batch_processor

importlib.reload(batch_processor)

OUTPUT_DIR = Path("../data/processed")

batch_processor.process_and_save_parquet(
    json_files=json_files,
    output_dir=OUTPUT_DIR,
)

Skipping 1/742: 90044961.parquet
Skipping 2/742: 90045719.parquet
Skipping 3/742: 90047087.parquet
Skipping 4/742: 90047777.parquet
Skipping 5/742: 90048477.parquet
Skipping 6/742: 90049136.parquet
Skipping 7/742: 90049182.parquet
Skipping 8/742: 90049831.parquet
Skipping 9/742: 90050528.parquet
Skipping 10/742: 90050564.parquet
Skipping 11/742: 90051224.parquet
Skipping 12/742: 90051928.parquet
Skipping 13/742: 90052608.parquet
Skipping 14/742: 90053286.parquet
Skipping 15/742: 90053305.parquet
Skipping 16/742: 90053308.parquet
Skipping 17/742: 90053977.parquet
Skipping 18/742: 90054009.parquet
Skipping 19/742: 90054012.parquet
Skipping 20/742: 90054683.parquet
Skipping 21/742: 90054702.parquet
Skipping 22/742: 90054709.parquet
Skipping 23/742: 90055318.parquet
Skipping 24/742: 90055363.parquet
Skipping 25/742: 90055371.parquet
Skipping 26/742: 90055388.parquet
Skipping 27/742: 90056002.parquet
Skipping 28/742: 90056044.parquet
Skipping 29/742: 90056057.parquet
Skipping 30/742: 90056068.parquet
Skipping 31/742: 90056702.parquet
Skipping 32/742: 90056744.parquet
Skipping 33/742: 90057399.parquet
Skipping 34/742: 90057438.parquet
Skipping 35/742: 90057459.parquet
Skipping 36/742: 90058080.parquet
Skipping 37/742: 90058124.parquet
Skipping 38/742: 90058142.parquet
Skipping 39/742: 90058773.parquet
Skipping 40/742: 90058809.parquet
Skipping 41/742: 90059468.parquet
Skipping 42/742: 90059492.parquet
Skipping 43/742: 90059498.parquet
Skipping 44/742: 90059519.parquet
Skipping 45/742: 90059520.parquet
Skipping 46/742: 90060164.parquet
Skipping 47/742: 90060204.parquet
Skipping 48/742: 90060866.parquet
Skipping 49/742: 90060904.parquet
Skipping 50/742: 90061533.parquet
Skipping 51/742: 90061574.parquet
Skipping 52/742: 90062216.parquet
Skipping 53/742: 90062899.parquet
Skipping 54/742: 90063533.parquet
Skipping 55/742: 90063564.parquet
Skipping 56/742: 90063594.parquet
Skipping 57/742: 90064228.parquet
Skipping 58/742: 90064254.parquet
Skipping 59/742: 90064905.parquet
Skipping 60/742: 90064934.parquet
Skipping 61/742: 90065576.parquet
Skipping 62/742: 90065613.parquet
Skipping 63/742: 90066283.parquet
Skipping 64/742: 90066318.parquet
Skipping 65/742: 90066956.parquet
Skipping 66/742: 90067625.parquet
Skipping 67/742: 90068302.parquet
Skipping 68/742: 90068973.parquet
Skipping 69/742: 90069646.parquet
Skipping 70/742: 90070322.parquet
Skipping 71/742: 90070944.parquet
Skipping 72/742: 90071607.parquet
Skipping 73/742: 90072319.parquet
Skipping 74/742: 90072987.parquet
Skipping 75/742: 90073646.parquet
Skipping 76/742: 90073673.parquet
Skipping 77/742: 90074322.parquet
Skipping 78/742: 90074337.parquet
Skipping 79/742: 90074984.parquet
Skipping 80/742: 90075682.parquet
Skipping 81/742: 90076352.parquet
Skipping 82/742: 90077041.parquet
Skipping 83/742: 90077708.parquet
Skipping 84/742: 90078409.parquet
Skipping 85/742: 90079749.parquet
Skipping 86/742: 90080414.parquet
Skipping 87/742: 90081107.parquet
Skipping 88/742: 90081772.parquet
Skipping 89/742: 90082450.parquet
Skipping 90/742: 90083130.parquet
Skipping 91/742: 90083792.parquet
Skipping 92/742: 90083801.parquet
Skipping 93/742: 90084447.parquet
Skipping 94/742: 90084475.parquet
Skipping 95/742: 90085126.parquet
Skipping 96/742: 90085153.parquet
Skipping 97/742: 90085808.parquet
Skipping 98/742: 90085836.parquet
Skipping 99/742: 90085846.parquet
Skipping 100/742: 90085850.parquet
Skipping 101/742: 90086527.parquet
Skipping 102/742: 90087910.parquet
Skipping 103/742: 90087915.parquet
Skipping 104/742: 90088570.parquet
Skipping 105/742: 90088604.parquet
Skipping 106/742: 90089255.parquet
Skipping 107/742: 90089945.parquet
Skipping 108/742: 90090620.parquet
Skipping 109/742: 90091318.parquet
Skipping 110/742: 90091996.parquet
Skipping 111/742: 90092680.parquet
Skipping 112/742: 90093362.parquet
Skipping 113/742: 90094062.parquet
Skipping 114/742: 90094726.parquet
Skipping 115/742: 90096778.parquet
Skipping 116/742: 90097448.parquet
Skipping 117/742: 90098090.parquet
Skipping 118/742: 90098103.parquet
Skipping 119/742: 90098133.parquet
Skipping 120/742: 90098806.parquet
Skipping 121/742: 90098812.parquet
Skipping 122/742: 90099453.parquet
Skipping 123/742: 90099464.parquet
Skipping 124/742: 90100144.parquet
Skipping 125/742: 90100801.parquet
Skipping 126/742: 90100814.parquet
Skipping 127/742: 90100828.parquet
Skipping 128/742: 90100854.parquet
Skipping 129/742: 90101487.parquet
Skipping 130/742: 90101498.parquet
Skipping 131/742: 90101500.parquet
Skipping 132/742: 90102167.parquet
Skipping 133/742: 90102181.parquet
Skipping 134/742: 90102197.parquet
Skipping 135/742: 90102198.parquet
Skipping 136/742: 90102201.parquet
Skipping 137/742: 90102872.parquet
Skipping 138/742: 90103567.parquet
Skipping 139/742: 90103574.parquet
Skipping 140/742: 90104259.parquet
Skipping 141/742: 90104911.parquet
Skipping 142/742: 90104951.parquet
Skipping 143/742: 90104954.parquet
Skipping 144/742: 90105616.parquet
Skipping 145/742: 90106312.parquet
Skipping 146/742: 90106988.parquet
Skipping 147/742: 90107666.parquet
Skipping 148/742: 90107681.parquet
Skipping 149/742: 90108353.parquet
Skipping 150/742: 90109040.parquet
Skipping 151/742: 90109720.parquet
Skipping 152/742: 90110400.parquet
Skipping 153/742: 90117853.parquet
Skipping 154/742: 90118542.parquet
Skipping 155/742: 90121273.parquet
Skipping 156/742: 90121943.parquet
Skipping 157/742: 90124682.parquet
Skipping 158/742: 90126740.parquet
Skipping 159/742: 90128767.parquet
Skipping 160/742: 90128769.parquet
Skipping 161/742: 90130811.parquet
Skipping 162/742: 90130822.parquet
Skipping 163/742: 90132865.parquet
Skipping 164/742: 90133551.parquet
Skipping 165/742: 90134231.parquet
Skipping 166/742: 90134236.parquet
Skipping 167/742: 90134923.parquet
Skipping 168/742: 90137605.parquet
Skipping 169/742: 90139722.parquet
Skipping 170/742: 90141058.parquet
Skipping 171/742: 90141100.parquet
Skipping 172/742: 90141770.parquet
Skipping 173/742: 90142472.parquet
Skipping 174/742: 90143176.parquet
Skipping 175/742: 90143864.parquet
Skipping 176/742: 90144556.parquet
Skipping 177/742: 90145269.parquet
Skipping 178/742: 90145960.parquet
Skipping 179/742: 90146571.parquet
Skipping 180/742: 90146644.parquet
Skipping 181/742: 90147327.parquet
Skipping 182/742: 90147942.parquet
Skipping 183/742: 90147961.parquet
Skipping 184/742: 90148025.parquet
Skipping 185/742: 90148658.parquet
Skipping 186/742: 90148707.parquet
Skipping 187/742: 90149323.parquet
Skipping 188/742: 90149344.parquet
Skipping 189/742: 90150023.parquet
Skipping 190/742: 90150049.parquet
Skipping 191/742: 90150716.parquet
Skipping 192/742: 90150738.parquet
Skipping 193/742: 90151402.parquet
Skipping 194/742: 90151422.parquet
Skipping 195/742: 90152071.parquet
Skipping 196/742: 90152097.parquet
Skipping 197/742: 90152825.parquet
Skipping 198/742: 90153442.parquet
Skipping 199/742: 90153469.parquet
Skipping 200/742: 90153480.parquet
Skipping 201/742: 90153504.parquet
Skipping 202/742: 90154127.parquet
Skipping 203/742: 90154148.parquet
Skipping 204/742: 90154808.parquet
Skipping 205/742: 90154835.parquet
Skipping 206/742: 90155488.parquet
Skipping 207/742: 90155493.parquet
Skipping 208/742: 90155518.parquet
Skipping 209/742: 90155519.parquet
Skipping 210/742: 90156175.parquet
Skipping 211/742: 90156178.parquet
Skipping 212/742: 90156211.parquet
Skipping 213/742: 90156857.parquet
Skipping 214/742: 90156866.parquet
Skipping 215/742: 90156883.parquet
Skipping 216/742: 90156919.parquet
Skipping 217/742: 90157554.parquet
Skipping 218/742: 90157565.parquet
Skipping 219/742: 90157591.parquet
Skipping 220/742: 90158257.parquet
Skipping 221/742: 90158259.parquet
Skipping 222/742: 90158270.parquet
Skipping 223/742: 90158292.parquet
Skipping 224/742: 90158312.parquet
Skipping 225/742: 90158972.parquet
Skipping 226/742: 90158973.parquet
Skipping 227/742: 90158981.parquet
Skipping 228/742: 90159672.parquet
Skipping 229/742: 90159674.parquet
Skipping 230/742: 90159693.parquet
Skipping 231/742: 90160367.parquet
Skipping 232/742: 90160373.parquet
Skipping 233/742: 90161052.parquet
Skipping 234/742: 90161060.parquet
Skipping 235/742: 90161683.parquet
Skipping 236/742: 90161746.parquet
Skipping 237/742: 90162376.parquet
Skipping 238/742: 90163074.parquet
Skipping 239/742: 90163769.parquet
Skipping 240/742: 90164461.parquet
Skipping 241/742: 90165148.parquet
Skipping 242/742: 90165193.parquet
Skipping 243/742: 90165194.parquet
Skipping 244/742: 90165858.parquet
Skipping 245/742: 90166548.parquet
Skipping 246/742: 90167254.parquet
Skipping 247/742: 90167953.parquet
Skipping 248/742: 90168654.parquet
Skipping 249/742: 90169370.parquet
Skipping 250/742: 90170085.parquet
Skipping 251/742: 90170097.parquet
Skipping 252/742: 90170722.parquet
Skipping 253/742: 90170793.parquet
Skipping 254/742: 90171433.parquet
Skipping 255/742: 90171442.parquet
Skipping 256/742: 90172140.parquet
Skipping 257/742: 90172847.parquet
Skipping 258/742: 90172856.parquet
Skipping 259/742: 90173560.parquet
Skipping 260/742: 90173577.parquet
Skipping 261/742: 90173578.parquet
Skipping 262/742: 90174249.parquet
Skipping 263/742: 90174276.parquet
Skipping 264/742: 90175032.parquet
Skipping 265/742: 90178520.parquet
Skipping 266/742: 90178526.parquet
Skipping 267/742: 90179860.parquet
Skipping 268/742: 90180558.parquet
Skipping 269/742: 90181276.parquet
Skipping 270/742: 90181298.parquet
Skipping 271/742: 90182006.parquet
Skipping 272/742: 90182640.parquet
Skipping 273/742: 90182668.parquet
Skipping 274/742: 90183389.parquet
Skipping 275/742: 90184051.parquet
Skipping 276/742: 90184095.parquet
Skipping 277/742: 90184098.parquet
Skipping 278/742: 90184765.parquet
Skipping 279/742: 90184806.parquet
Skipping 280/742: 90185459.parquet
Skipping 281/742: 90185504.parquet
Skipping 282/742: 90185506.parquet
Skipping 283/742: 90186182.parquet
Skipping 284/742: 90186209.parquet
Skipping 285/742: 90186217.parquet
Skipping 286/742: 90186885.parquet
Skipping 287/742: 90186923.parquet
Skipping 288/742: 90187584.parquet
Skipping 289/742: 90188276.parquet
Skipping 290/742: 90188298.parquet
Skipping 291/742: 90188328.parquet
Skipping 292/742: 90188334.parquet
Skipping 293/742: 90188991.parquet
Skipping 294/742: 90189013.parquet
Skipping 295/742: 90189698.parquet
Skipping 296/742: 90189728.parquet
Skipping 297/742: 90190430.parquet
Skipping 298/742: 90190446.parquet
Skipping 299/742: 90191165.parquet
Skipping 300/742: 90191865.parquet
Skipping 301/742: 90192562.parquet
Skipping 302/742: 90192566.parquet
Skipping 303/742: 90192570.parquet
Skipping 304/742: 90193179.parquet
Skipping 305/742: 90193249.parquet
Skipping 306/742: 90193288.parquet
Skipping 307/742: 90193976.parquet
Skipping 308/742: 90194686.parquet
Skipping 309/742: 90194722.parquet
Skipping 310/742: 90195365.parquet
Skipping 311/742: 90195407.parquet
Skipping 312/742: 90196094.parquet
Skipping 313/742: 90196118.parquet
Skipping 314/742: 90196844.parquet
Skipping 315/742: 90197584.parquet
Skipping 316/742: 90198283.parquet
Skipping 317/742: 90198309.parquet
Skipping 318/742: 90199002.parquet
Skipping 319/742: 90199014.parquet
Skipping 320/742: 90199038.parquet
Skipping 321/742: 90199745.parquet
Skipping 322/742: 90200473.parquet
Skipping 323/742: 90200474.parquet
Skipping 324/742: 90200486.parquet
Skipping 325/742: 90201202.parquet
Skipping 326/742: 90201203.parquet
Skipping 327/742: 90205310.parquet
Skipping 328/742: 90206035.parquet
Skipping 329/742: 90206772.parquet
Skipping 330/742: 90207493.parquet
Skipping 331/742: 90208223.parquet
Skipping 332/742: 90208944.parquet
Skipping 333/742: 90208964.parquet
Skipping 334/742: 90209716.parquet
Skipping 335/742: 90210407.parquet
Skipping 336/742: 90210459.parquet
Skipping 337/742: 90210475.parquet
Skipping 338/742: 90211148.parquet
Skipping 339/742: 90211207.parquet
Skipping 340/742: 90211875.parquet
Skipping 341/742: 90211931.parquet
Skipping 342/742: 90211932.parquet
Skipping 343/742: 90212606.parquet
Skipping 344/742: 90212622.parquet
Skipping 345/742: 90213350.parquet
Skipping 346/742: 90213369.parquet
Skipping 347/742: 90214096.parquet
Skipping 348/742: 90214112.parquet
Skipping 349/742: 90214152.parquet
Skipping 350/742: 90214160.parquet
Skipping 351/742: 90214829.parquet
Skipping 352/742: 90214841.parquet
Skipping 353/742: 90215568.parquet
Skipping 354/742: 90215583.parquet
Skipping 355/742: 90215588.parquet
Skipping 356/742: 90216317.parquet
Skipping 357/742: 90216325.parquet
Skipping 358/742: 90216337.parquet
Skipping 359/742: 90217017.parquet
Skipping 360/742: 90217026.parquet
Skipping 361/742: 90217042.parquet
Skipping 362/742: 90217688.parquet
Skipping 363/742: 90217699.parquet
Skipping 364/742: 90217713.parquet
Skipping 365/742: 90218412.parquet
Skipping 366/742: 90218423.parquet
Skipping 367/742: 90219144.parquet
Skipping 368/742: 90219149.parquet
Skipping 369/742: 90219839.parquet
Skipping 370/742: 90219883.parquet
Skipping 371/742: 90220545.parquet
Skipping 372/742: 90220571.parquet
Skipping 373/742: 90221261.parquet
Skipping 374/742: 90221974.parquet
Skipping 375/742: 90221980.parquet
Skipping 376/742: 90222014.parquet
Skipping 377/742: 90222697.parquet
Skipping 378/742: 90222729.parquet
Skipping 379/742: 90223426.parquet
Skipping 380/742: 90224138.parquet
Skipping 381/742: 90224161.parquet
Skipping 382/742: 90224829.parquet
Skipping 383/742: 90224857.parquet
Skipping 384/742: 90224865.parquet
Skipping 385/742: 90225559.parquet
Skipping 386/742: 90225603.parquet
Skipping 387/742: 90226946.parquet
Skipping 388/742: 90226992.parquet
Skipping 389/742: 90227000.parquet
Skipping 390/742: 90227023.parquet
Skipping 391/742: 90227027.parquet
Skipping 392/742: 90227677.parquet
Skipping 393/742: 90227706.parquet
Skipping 394/742: 90227713.parquet
Skipping 395/742: 90228370.parquet
Skipping 396/742: 90228412.parquet
Skipping 397/742: 90228424.parquet
Skipping 398/742: 90228431.parquet
Skipping 399/742: 90228456.parquet
Skipping 400/742: 90228460.parquet
Skipping 401/742: 90229090.parquet
Skipping 402/742: 90229145.parquet
Skipping 403/742: 90229153.parquet
Skipping 404/742: 90229816.parquet
Skipping 405/742: 90229820.parquet
Skipping 406/742: 90229871.parquet
Skipping 407/742: 90229875.parquet
Skipping 408/742: 90230535.parquet
Skipping 409/742: 90230582.parquet
Skipping 410/742: 90231260.parquet
Skipping 411/742: 90231306.parquet
Skipping 412/742: 90231957.parquet
Skipping 413/742: 90231961.parquet
Skipping 414/742: 90232683.parquet
Skipping 415/742: 90232731.parquet
Skipping 416/742: 90232735.parquet
Skipping 417/742: 90233408.parquet
Skipping 418/742: 90233409.parquet
Skipping 419/742: 90233445.parquet
Skipping 420/742: 90234091.parquet
Skipping 421/742: 90234096.parquet
Skipping 422/742: 90234827.parquet
Skipping 423/742: 90234836.parquet
Skipping 424/742: 90234864.parquet
Skipping 425/742: 90235554.parquet
Skipping 426/742: 90236276.parquet
Skipping 427/742: 90236302.parquet
Skipping 428/742: 90236984.parquet
Skipping 429/742: 90238409.parquet
Skipping 430/742: 90238433.parquet
Skipping 431/742: 90239123.parquet
Skipping 432/742: 90239821.parquet
Skipping 433/742: 90239831.parquet
Skipping 434/742: 90240529.parquet
Skipping 435/742: 90240543.parquet
Skipping 436/742: 90241873.parquet
Skipping 437/742: 90241978.parquet
Skipping 438/742: 90241988.parquet
Skipping 439/742: 90242579.parquet
Skipping 440/742: 90242657.parquet
Skipping 441/742: 90243288.parquet
Skipping 442/742: 90243367.parquet
Skipping 443/742: 90243999.parquet
Skipping 444/742: 90244085.parquet
Skipping 445/742: 90244091.parquet
Skipping 446/742: 90244099.parquet
Skipping 447/742: 90244110.parquet
Skipping 448/742: 90244717.parquet
Skipping 449/742: 90245428.parquet
Skipping 450/742: 90245429.parquet
Skipping 451/742: 90245487.parquet
Skipping 452/742: 90245489.parquet
Skipping 453/742: 90245509.parquet
Skipping 454/742: 90245513.parquet
Skipping 455/742: 90246130.parquet
Skipping 456/742: 90246133.parquet
Skipping 457/742: 90246217.parquet
Skipping 458/742: 90246849.parquet
Skipping 459/742: 90246896.parquet
Skipping 460/742: 90246903.parquet
Skipping 461/742: 90246927.parquet
Skipping 462/742: 90246948.parquet
Skipping 463/742: 90247518.parquet
Skipping 464/742: 90247551.parquet
Skipping 465/742: 90247614.parquet
Skipping 466/742: 90247647.parquet
Skipping 467/742: 90248229.parquet
Skipping 468/742: 90248255.parquet
Skipping 469/742: 90248261.parquet
Skipping 470/742: 90248940.parquet
Skipping 471/742: 90248957.parquet
Skipping 472/742: 90248963.parquet
Skipping 473/742: 90249059.parquet
Skipping 474/742: 90249063.parquet
Skipping 475/742: 90249693.parquet
Skipping 476/742: 90249697.parquet
Skipping 477/742: 90250386.parquet
Skipping 478/742: 90250406.parquet
Skipping 479/742: 90250408.parquet
Skipping 480/742: 90250447.parquet
Skipping 481/742: 90250452.parquet
Skipping 482/742: 90250471.parquet
Skipping 483/742: 90250478.parquet
Skipping 484/742: 90250479.parquet
Skipping 485/742: 90251113.parquet
Skipping 486/742: 90251127.parquet
Skipping 487/742: 90251134.parquet
Skipping 488/742: 90251142.parquet
Skipping 489/742: 90251207.parquet
Skipping 490/742: 90251825.parquet
Skipping 491/742: 90251853.parquet
Skipping 492/742: 90251858.parquet
Skipping 493/742: 90251922.parquet
Skipping 494/742: 90252545.parquet
Skipping 495/742: 90252559.parquet
Skipping 496/742: 90252565.parquet
Skipping 497/742: 90252576.parquet
Skipping 498/742: 90252636.parquet
Skipping 499/742: 90253257.parquet
Skipping 500/742: 90253274.parquet
Skipping 501/742: 90253285.parquet
Skipping 502/742: 90253341.parquet
Skipping 503/742: 90253968.parquet
Skipping 504/742: 90253986.parquet
Skipping 505/742: 90254020.parquet
Skipping 506/742: 90254050.parquet
Skipping 507/742: 90254684.parquet
Skipping 508/742: 90254702.parquet
Skipping 509/742: 90254705.parquet
Skipping 510/742: 90254720.parquet
Skipping 511/742: 90255404.parquet
Skipping 512/742: 90255430.parquet
Skipping 513/742: 90256132.parquet
Skipping 514/742: 90256834.parquet
Skipping 515/742: 90256858.parquet
Skipping 516/742: 90256883.parquet
Skipping 517/742: 90256889.parquet
Skipping 518/742: 90257567.parquet
Skipping 519/742: 90257614.parquet
Skipping 520/742: 90258281.parquet
Skipping 521/742: 90258947.parquet
Skipping 522/742: 90258999.parquet
Skipping 523/742: 90259027.parquet
Skipping 524/742: 90259047.parquet
Skipping 525/742: 90259656.parquet
Skipping 526/742: 90259704.parquet
Skipping 527/742: 90260370.parquet
Skipping 528/742: 90260417.parquet
Skipping 529/742: 90260447.parquet
Skipping 530/742: 90260457.parquet
Skipping 531/742: 90261091.parquet
Skipping 532/742: 90261132.parquet
Skipping 533/742: 90261160.parquet
Skipping 534/742: 90261185.parquet
Skipping 535/742: 90261804.parquet
Skipping 536/742: 90262515.parquet
Skipping 537/742: 90263191.parquet
Skipping 538/742: 90263289.parquet
Skipping 539/742: 90263291.parquet
Skipping 540/742: 90263313.parquet
Skipping 541/742: 90263905.parquet
Skipping 542/742: 90263947.parquet
Skipping 543/742: 90263988.parquet
Skipping 544/742: 90264619.parquet
Skipping 545/742: 90264668.parquet
Skipping 546/742: 90265334.parquet
Skipping 547/742: 90265401.parquet
Skipping 548/742: 90265404.parquet
Skipping 549/742: 90265432.parquet
Skipping 550/742: 90265433.parquet
Skipping 551/742: 90266052.parquet
Skipping 552/742: 90266097.parquet
Skipping 553/742: 90266099.parquet
Skipping 554/742: 90266125.parquet
Skipping 555/742: 90266159.parquet
Skipping 556/742: 90266768.parquet
Skipping 557/742: 90266771.parquet
Skipping 558/742: 90266815.parquet
Skipping 559/742: 90266864.parquet
Skipping 560/742: 90267485.parquet
Skipping 561/742: 90267524.parquet
Skipping 562/742: 90267571.parquet
Skipping 563/742: 90268200.parquet
Skipping 564/742: 90268205.parquet
Skipping 565/742: 90268259.parquet
Skipping 566/742: 90268263.parquet
Skipping 567/742: 90268933.parquet
Skipping 568/742: 90268935.parquet
Skipping 569/742: 90268986.parquet
Skipping 570/742: 90268993.parquet
Skipping 571/742: 90268997.parquet
Skipping 572/742: 90269653.parquet
Skipping 573/742: 90269711.parquet
Skipping 574/742: 90269744.parquet

In [264]:
parquet_files = sorted(OUTPUT_DIR.glob("*.parquet"))

print("Parquet files created:", len(parquet_files))

for file in parquet_files:
    print(file.name)

Parquet files created: 742
90044961.parquet
90045719.parquet
90047087.parquet
90047777.parquet
90048477.parquet
90049136.parquet
90049182.parquet
90049831.parquet
90050528.parquet
90050564.parquet
90051224.parquet
90051928.parquet
90052608.parquet
90053286.parquet
90053305.parquet
90053308.parquet
90053977.parquet
90054009.parquet
90054012.parquet
90054683.parquet
90054702.parquet
90054709.parquet
90055318.parquet
90055363.parquet
90055371.parquet
90055388.parquet
90056002.parquet
90056044.parquet
90056057.parquet
90056068.parquet
90056702.parquet
90056744.parquet
90057399.parquet
90057438.parquet
90057459.parquet
90058080.parquet
90058124.parquet
90058142.parquet
90058773.parquet
90058809.parquet
90059468.parquet
90059492.parquet
90059498.parquet
90059519.parquet
90059520.parquet
90060164.parquet
90060204.parquet
90060866.parquet
90060904.parquet
90061533.parquet
90061574.parquet
90062216.parquet
90062899.parquet
90063533.parquet
90063564.parquet
90063594.parquet
90064228.parquet
90064254.parquet
90064905.parquet
90064934.parquet
90065576.parquet
90065613.parquet
90066283.parquet
90066318.parquet
90066956.parquet
90067625.parquet
90068302.parquet
90068973.parquet
90069646.parquet
90070322.parquet
90070944.parquet
90071607.parquet
90072319.parquet
90072987.parquet
90073646.parquet
90073673.parquet
90074322.parquet
90074337.parquet
90074984.parquet
90075682.parquet
90076352.parquet
90077041.parquet
90077708.parquet
90078409.parquet
90079749.parquet
90080414.parquet
90081107.parquet
90081772.parquet
90082450.parquet
90083130.parquet
90083792.parquet
90083801.parquet
90084447.parquet
90084475.parquet
90085126.parquet
90085153.parquet
90085808.parquet
90085836.parquet
90085846.parquet
90085850.parquet
90086527.parquet
90087910.parquet
90087915.parquet
90088570.parquet
90088604.parquet
90089255.parquet
90089945.parquet
90090620.parquet
90091318.parquet
90091996.parquet
90092680.parquet
90093362.parquet
90094062.parquet
90094726.parquet
90096778.parquet
90097448.parquet
90098090.parquet
90098103.parquet
90098133.parquet
90098806.parquet
90098812.parquet
90099453.parquet
90099464.parquet
90100144.parquet
90100801.parquet
90100814.parquet
90100828.parquet
90100854.parquet
90101487.parquet
90101498.parquet
90101500.parquet
90102167.parquet
90102181.parquet
90102197.parquet
90102198.parquet
90102201.parquet
90102872.parquet
90103567.parquet
90103574.parquet
90104259.parquet
90104911.parquet
90104951.parquet
90104954.parquet
90105616.parquet
90106312.parquet
90106988.parquet
90107666.parquet
90107681.parquet
90108353.parquet
90109040.parquet
90109720.parquet
90110400.parquet
90117853.parquet
90118542.parquet
90121273.parquet
90121943.parquet
90124682.parquet
90126740.parquet
90128767.parquet
90128769.parquet
90130811.parquet
90130822.parquet
90132865.parquet
90133551.parquet
90134231.parquet
90134236.parquet
90134923.parquet
90137605.parquet
90139722.parquet
90141058.parquet
90141100.parquet
90141770.parquet
90142472.parquet
90143176.parquet
90143864.parquet
90144556.parquet
90145269.parquet
90145960.parquet
90146571.parquet
90146644.parquet
90147327.parquet
90147942.parquet
90147961.parquet
90148025.parquet
90148658.parquet
90148707.parquet
90149323.parquet
90149344.parquet
90150023.parquet
90150049.parquet
90150716.parquet
90150738.parquet
90151402.parquet
90151422.parquet
90152071.parquet
90152097.parquet
90152825.parquet
90153442.parquet
90153469.parquet
90153480.parquet
90153504.parquet
90154127.parquet
90154148.parquet
90154808.parquet
90154835.parquet
90155488.parquet
90155493.parquet
90155518.parquet
90155519.parquet
90156175.parquet
90156178.parquet
90156211.parquet
90156857.parquet
90156866.parquet
90156883.parquet
90156919.parquet
90157554.parquet
90157565.parquet
90157591.parquet
90158257.parquet
90158259.parquet
90158270.parquet
90158292.parquet
90158312.parquet
90158972.parquet
90158973.parquet
90158981.parquet
90159672.parquet
90159674.parquet
90159693.parquet
90160367.parquet
90160373.parquet
90161052.parquet
90161060.parquet
90161683.parquet
90161746.parquet
90162376.parquet
90163074.parquet
90163769.parquet
90164461.parquet
90165148.parquet
90165193.parquet
90165194.parquet
90165858.parquet
90166548.parquet
90167254.parquet
90167953.parquet
90168654.parquet
90169370.parquet
90170085.parquet
90170097.parquet
90170722.parquet
90170793.parquet
90171433.parquet
90171442.parquet
90172140.parquet
90172847.parquet
90172856.parquet
90173560.parquet
90173577.parquet
90173578.parquet
90174249.parquet
90174276.parquet
90175032.parquet
90178520.parquet
90178526.parquet
90179860.parquet
90180558.parquet
90181276.parquet
90181298.parquet
90182006.parquet
90182640.parquet
90182668.parquet
90183389.parquet
90184051.parquet
90184095.parquet
90184098.parquet
90184765.parquet
90184806.parquet
90185459.parquet
90185504.parquet
90185506.parquet
90186182.parquet
90186209.parquet
90186217.parquet
90186885.parquet
90186923.parquet
90187584.parquet
90188276.parquet
90188298.parquet
90188328.parquet
90188334.parquet
90188991.parquet
90189013.parquet
90189698.parquet
90189728.parquet
90190430.parquet
90190446.parquet
90191165.parquet
90191865.parquet
90192562.parquet
90192566.parquet
90192570.parquet
90193179.parquet
90193249.parquet
90193288.parquet
90193976.parquet
90194686.parquet
90194722.parquet
90195365.parquet
90195407.parquet
90196094.parquet
90196118.parquet
90196844.parquet
90197584.parquet
90198283.parquet
90198309.parquet
90199002.parquet
90199014.parquet
90199038.parquet
90199745.parquet
90200473.parquet
90200474.parquet
90200486.parquet
90201202.parquet
90201203.parquet
90205310.parquet
90206035.parquet
90206772.parquet
90207493.parquet
90208223.parquet
90208944.parquet
90208964.parquet
90209716.parquet
90210407.parquet
90210459.parquet
90210475.parquet
90211148.parquet
90211207.parquet
90211875.parquet
90211931.parquet
90211932.parquet
90212606.parquet
90212622.parquet
90213350.parquet
90213369.parquet
90214096.parquet
90214112.parquet
90214152.parquet
90214160.parquet
90214829.parquet
90214841.parquet
90215568.parquet
90215583.parquet
90215588.parquet
90216317.parquet
90216325.parquet
90216337.parquet
90217017.parquet
90217026.parquet
90217042.parquet
90217688.parquet
90217699.parquet
90217713.parquet
90218412.parquet
90218423.parquet
90219144.parquet
90219149.parquet
90219839.parquet
90219883.parquet
90220545.parquet
90220571.parquet
90221261.parquet
90221974.parquet
90221980.parquet
90222014.parquet
90222697.parquet
90222729.parquet
90223426.parquet
90224138.parquet
90224161.parquet
90224829.parquet
90224857.parquet
90224865.parquet
90225559.parquet
90225603.parquet
90226946.parquet
90226992.parquet
90227000.parquet
90227023.parquet
90227027.parquet
90227677.parquet
90227706.parquet
90227713.parquet
90228370.parquet
90228412.parquet
90228424.parquet
90228431.parquet
90228456.parquet
90228460.parquet
90229090.parquet
90229145.parquet
90229153.parquet
90229816.parquet
90229820.parquet
90229871.parquet
90229875.parquet
90230535.parquet
90230582.parquet
90231260.parquet
90231306.parquet
90231957.parquet
90231961.parquet
90232683.parquet
90232731.parquet
90232735.parquet
90233408.parquet
90233409.parquet
90233445.parquet
90234091.parquet
90234096.parquet
90234827.parquet
90234836.parquet
90234864.parquet
90235554.parquet
90236276.parquet
90236302.parquet
90236984.parquet
90238409.parquet
90238433.parquet
90239123.parquet
90239821.parquet
90239831.parquet
90240529.parquet
90240543.parquet
90241873.parquet
90241978.parquet
90241988.parquet
90242579.parquet
90242657.parquet
90243288.parquet
90243367.parquet
90243999.parquet
90244085.parquet
90244091.parquet
90244099.parquet
90244110.parquet
90244717.parquet
90245428.parquet
90245429.parquet
90245487.parquet
90245489.parquet
90245509.parquet
90245513.parquet
90246130.parquet
90246133.parquet
90246217.parquet
90246849.parquet
90246896.parquet
90246903.parquet
90246927.parquet
90246948.parquet
90247518.parquet
90247551.parquet
90247614.parquet
90247647.parquet
90248229.parquet
90248255.parquet
90248261.parquet
90248940.parquet
90248957.parquet
90248963.parquet
90249059.parquet
90249063.parquet
90249693.parquet
90249697.parquet
90250386.parquet
90250406.parquet
90250408.parquet
90250447.parquet
90250452.parquet
90250471.parquet
90250478.parquet
90250479.parquet
90251113.parquet
90251127.parquet
90251134.parquet
90251142.parquet
90251207.parquet
90251825.parquet
90251853.parquet
90251858.parquet
90251922.parquet
90252545.parquet
90252559.parquet
90252565.parquet
90252576.parquet
90252636.parquet
90253257.parquet
90253274.parquet
90253285.parquet
90253341.parquet
90253968.parquet
90253986.parquet
90254020.parquet
90254050.parquet
90254684.parquet
90254702.parquet
90254705.parquet
90254720.parquet
90255404.parquet
90255430.parquet
90256132.parquet
90256834.parquet
90256858.parquet
90256883.parquet
90256889.parquet
90257567.parquet
90257614.parquet
90258281.parquet
90258947.parquet
90258999.parquet
90259027.parquet
90259047.parquet
90259656.parquet
90259704.parquet
90260370.parquet
90260417.parquet
90260447.parquet
90260457.parquet
90261091.parquet
90261132.parquet
90261160.parquet
90261185.parquet
90261804.parquet
90262515.parquet
90263191.parquet
90263289.parquet
90263291.parquet
90263313.parquet
90263905.parquet
90263947.parquet
90263988.parquet
90264619.parquet
90264668.parquet
90265334.parquet
90265401.parquet
90265404.parquet
90265432.parquet
90265433.parquet
90266052.parquet
90266097.parquet
90266099.parquet
90266125.parquet
90266159.parquet
90266768.parquet
90266771.parquet
90266815.parquet
90266864.parquet
90267485.parquet
90267524.parquet
90267571.parquet
90268200.parquet
90268205.parquet
90268259.parquet
90268263.parquet
90268933.parquet
90268935.parquet
90268986.parquet
90268993.parquet
90268997.parquet
90269653.parquet
90269711.parquet
90269744.parquet
90270374.parquet
90270451.parquet
90271098.parquet
90271104.parquet
90271149.parquet
90271176.parquet
90271814.parquet
90271823.parquet
90271856.parquet
90271889.parquet
90272534.parquet
90272535.parquet
90272579.parquet
90272605.parquet
90273248.parquet
90273262.parquet
90273325.parquet
90273957.parquet
90273999.parquet
90274663.parquet
90274672.parquet
90274689.parquet
90274697.parquet
90274717.parquet
90274719.parquet
90274733.parquet
90275376.parquet
90275377.parquet
90275403.parquet
90276099.parquet
90276102.parquet
90276121.parquet
90276153.parquet
90276173.parquet
90276179.parquet
90276822.parquet
90276826.parquet
90277479.parquet
90277534.parquet
90277536.parquet
90277580.parquet
90277601.parquet
90278249.parquet
90278250.parquet
90278289.parquet
90278295.parquet
90278963.parquet
90278965.parquet
90278991.parquet
90279616.parquet
90279722.parquet
90280453.parquet
90280458.parquet
90280460.parquet
90280463.parquet
90280479.parquet
90280483.parquet
90281048.parquet
90281187.parquet
90281781.parquet
90281855.parquet
90281858.parquet
90281874.parquet
90281879.parquet
90282486.parquet
90282506.parquet
90282508.parquet
90283186.parquet
90283210.parquet
90283226.parquet
90283274.parquet
90283301.parquet
90283932.parquet
90283949.parquet
90283995.parquet
90283999.parquet
90284035.parquet
90284042.parquet
90284045.parquet
90284046.parquet
90284623.parquet
90284651.parquet
90284670.parquet
90285372.parquet
90285393.parquet
90285399.parquet
90285442.parquet
90285497.parquet
90286070.parquet
90286093.parquet
90286115.parquet
90286116.parquet
90286174.parquet
90286189.parquet
90286795.parquet
90286817.parquet
90286872.parquet
90286914.parquet
90287512.parquet
90287537.parquet
90287560.parquet
90287637.parquet
90288225.parquet
90288241.parquet
90288253.parquet
90288280.parquet
90288332.parquet
90288368.parquet
90288936.parquet
90288945.parquet
90288973.parquet
90288993.parquet
90288997.parquet
90289025.parquet
90289063.parquet
90289073.parquet
90289667.parquet
90289674.parquet
90289688.parquet
90289707.parquet
90289727.parquet
90289741.parquet
90289772.parquet
90289799.parquet
90290379.parquet
90290392.parquet
90290397.parquet
90290412.parquet
90290424.parquet
90290449.parquet
90291096.parquet
90291106.parquet
90291114.parquet
90291126.parquet
90291136.parquet
90291162.parquet
90291195.parquet
90291227.parquet
90291247.parquet
90291828.parquet
90291837.parquet
90291849.parquet
90291861.parquet
90291886.parquet
90291899.parquet
90292555.parquet
90292567.parquet
90292578.parquet
90292587.parquet
90292595.parquet
90292606.parquet
90292618.parquet
90292619.parquet
90292711.parquet
90293276.parquet
90293285.parquet
90293295.parquet
90293304.parquet
90293309.parquet
90293340.parquet
90293422.parquet
90294010.parquet
90294019.parquet
90294027.parquet
90294038.parquet
90294045.parquet
90294077.parquet
90294158.parquet

In [265]:
test_parquet = pd.read_parquet(parquet_files[0])

print("Shape:", test_parquet.shape)
print("Columns:", len(test_parquet.columns))

test_parquet.tail(5)

Shape: (1440, 64)
Columns: 64

,episode_id,player,step,day,hour,money,farmer_x,farmer_y,hires_today,remaining_overage_time,...,goose_count,total_plant_yield,total_pasture_yield,watered_plant_count,unwatered_plant_count,fertilized_plant_count,fed_animal_count,unfed_animal_count,cared_animal_count,uncared_animal_count
1435,c6bc5296-9060-11f1-814b-0242ac130202,1,717,29,21,151851.0,5,4,12,57.12553,...,0,2,0,0,6,6,0,14,0,14
1436,c6bc5296-9060-11f1-814b-0242ac130202,0,718,29,22,151852.0,5,4,12,60.00000,...,0,2,0,0,7,7,0,14,0,14
1437,c6bc5296-9060-11f1-814b-0242ac130202,1,718,29,22,152441.0,5,4,12,57.12553,...,0,2,0,0,6,6,0,14,0,14
1438,c6bc5296-9060-11f1-814b-0242ac130202,0,719,29,23,151880.0,5,4,12,60.00000,...,0,2,0,0,7,7,0,14,0,14
1439,c6bc5296-9060-11f1-814b-0242ac130202,1,719,29,23,152469.0,5,4,12,57.12553,...,0,2,0,0,6,6,0,14,0,14

In [266]:
parquet_files = sorted(OUTPUT_DIR.glob("*.parquet"))

print("Total Parquet files:", len(parquet_files))
print("Expected JSON files:", len(json_files))

Total Parquet files: 742
Expected JSON files: 742

In [267]:
json_stems = {file.stem for file in json_files}
parquet_stems = {file.stem for file in parquet_files}

missing = json_stems - parquet_stems

print("Missing processed files:", len(missing))

if missing:
    print(missing)
else:
    print("All JSON files were processed successfully ✅")

Missing processed files: 0
All JSON files were processed successfully ✅

In [268]:
df = pd.read_parquet(parquet_files[0])

print("Shape:", df.shape)
print("Columns:", len(df.columns))
print("Missing values:", df.isnull().sum().sum())

Shape: (1440, 64)
Columns: 64
Missing values: 0

In [269]:
import sys

sys.path.append("..")

from src.validation.data_validation import validate_dataset

In [270]:
from pathlib import Path

processed_dir = Path("../data/processed")

validation_df = validate_dataset(processed_dir)

validation_df.head()

Found 742 Parquet files
Validating 1/742: 90044961.parquet
Validating 2/742: 90045719.parquet
Validating 3/742: 90047087.parquet
Validating 4/742: 90047777.parquet
Validating 5/742: 90048477.parquet
Validating 6/742: 90049136.parquet
Validating 7/742: 90049182.parquet
Validating 8/742: 90049831.parquet
Validating 9/742: 90050528.parquet
Validating 10/742: 90050564.parquet
Validating 11/742: 90051224.parquet
Validating 12/742: 90051928.parquet
Validating 13/742: 90052608.parquet
Validating 14/742: 90053286.parquet
Validating 15/742: 90053305.parquet
Validating 16/742: 90053308.parquet
Validating 17/742: 90053977.parquet
Validating 18/742: 90054009.parquet
Validating 19/742: 90054012.parquet
Validating 20/742: 90054683.parquet
Validating 21/742: 90054702.parquet
Validating 22/742: 90054709.parquet
Validating 23/742: 90055318.parquet
Validating 24/742: 90055363.parquet
Validating 25/742: 90055371.parquet
Validating 26/742: 90055388.parquet
Validating 27/742: 90056002.parquet
Validating 28/742: 90056044.parquet
Validating 29/742: 90056057.parquet
Validating 30/742: 90056068.parquet
Validating 31/742: 90056702.parquet
Validating 32/742: 90056744.parquet
Validating 33/742: 90057399.parquet
Validating 34/742: 90057438.parquet
Validating 35/742: 90057459.parquet
Validating 36/742: 90058080.parquet
Validating 37/742: 90058124.parquet
Validating 38/742: 90058142.parquet
Validating 39/742: 90058773.parquet
Validating 40/742: 90058809.parquet
Validating 41/742: 90059468.parquet
Validating 42/742: 90059492.parquet
Validating 43/742: 90059498.parquet
Validating 44/742: 90059519.parquet
Validating 45/742: 90059520.parquet
Validating 46/742: 90060164.parquet
Validating 47/742: 90060204.parquet
Validating 48/742: 90060866.parquet
Validating 49/742: 90060904.parquet
Validating 50/742: 90061533.parquet
Validating 51/742: 90061574.parquet
Validating 52/742: 90062216.parquet
Validating 53/742: 90062899.parquet
Validating 54/742: 90063533.parquet
Validating 55/742: 90063564.parquet
Validating 56/742: 90063594.parquet
Validating 57/742: 90064228.parquet
Validating 58/742: 90064254.parquet
Validating 59/742: 90064905.parquet
Validating 60/742: 90064934.parquet
Validating 61/742: 90065576.parquet
Validating 62/742: 90065613.parquet
Validating 63/742: 90066283.parquet
Validating 64/742: 90066318.parquet
Validating 65/742: 90066956.parquet
Validating 66/742: 90067625.parquet
Validating 67/742: 90068302.parquet
Validating 68/742: 90068973.parquet
Validating 69/742: 90069646.parquet
Validating 70/742: 90070322.parquet
Validating 71/742: 90070944.parquet
Validating 72/742: 90071607.parquet
Validating 73/742: 90072319.parquet
Validating 74/742: 90072987.parquet
Validating 75/742: 90073646.parquet
Validating 76/742: 90073673.parquet
Validating 77/742: 90074322.parquet
Validating 78/742: 90074337.parquet
Validating 79/742: 90074984.parquet
Validating 80/742: 90075682.parquet
Validating 81/742: 90076352.parquet
Validating 82/742: 90077041.parquet
Validating 83/742: 90077708.parquet
Validating 84/742: 90078409.parquet
Validating 85/742: 90079749.parquet
Validating 86/742: 90080414.parquet
Validating 87/742: 90081107.parquet
Validating 88/742: 90081772.parquet
Validating 89/742: 90082450.parquet
Validating 90/742: 90083130.parquet
Validating 91/742: 90083792.parquet
Validating 92/742: 90083801.parquet
Validating 93/742: 90084447.parquet
Validating 94/742: 90084475.parquet
Validating 95/742: 90085126.parquet
Validating 96/742: 90085153.parquet
Validating 97/742: 90085808.parquet
Validating 98/742: 90085836.parquet
Validating 99/742: 90085846.parquet
Validating 100/742: 90085850.parquet
Validating 101/742: 90086527.parquet
Validating 102/742: 90087910.parquet
Validating 103/742: 90087915.parquet
Validating 104/742: 90088570.parquet
Validating 105/742: 90088604.parquet
Validating 106/742: 90089255.parquet
Validating 107/742: 90089945.parquet
Validating 108/742: 90090620.parquet
Validating 109/742: 90091318.parquet
Validating 110/742: 90091996.parquet
Validating 111/742: 90092680.parquet
Validating 112/742: 90093362.parquet
Validating 113/742: 90094062.parquet
Validating 114/742: 90094726.parquet
Validating 115/742: 90096778.parquet
Validating 116/742: 90097448.parquet
Validating 117/742: 90098090.parquet
Validating 118/742: 90098103.parquet
Validating 119/742: 90098133.parquet
Validating 120/742: 90098806.parquet
Validating 121/742: 90098812.parquet
Validating 122/742: 90099453.parquet
Validating 123/742: 90099464.parquet
Validating 124/742: 90100144.parquet
Validating 125/742: 90100801.parquet
Validating 126/742: 90100814.parquet
Validating 127/742: 90100828.parquet
Validating 128/742: 90100854.parquet
Validating 129/742: 90101487.parquet
Validating 130/742: 90101498.parquet
Validating 131/742: 90101500.parquet
Validating 132/742: 90102167.parquet
Validating 133/742: 90102181.parquet
Validating 134/742: 90102197.parquet
Validating 135/742: 90102198.parquet
Validating 136/742: 90102201.parquet
Validating 137/742: 90102872.parquet
Validating 138/742: 90103567.parquet
Validating 139/742: 90103574.parquet
Validating 140/742: 90104259.parquet
Validating 141/742: 90104911.parquet
Validating 142/742: 90104951.parquet
Validating 143/742: 90104954.parquet
Validating 144/742: 90105616.parquet
Validating 145/742: 90106312.parquet
Validating 146/742: 90106988.parquet
Validating 147/742: 90107666.parquet
Validating 148/742: 90107681.parquet
Validating 149/742: 90108353.parquet
Validating 150/742: 90109040.parquet
Validating 151/742: 90109720.parquet
Validating 152/742: 90110400.parquet
Validating 153/742: 90117853.parquet
Validating 154/742: 90118542.parquet
Validating 155/742: 90121273.parquet
Validating 156/742: 90121943.parquet
Validating 157/742: 90124682.parquet
Validating 158/742: 90126740.parquet
Validating 159/742: 90128767.parquet
Validating 160/742: 90128769.parquet
Validating 161/742: 90130811.parquet
Validating 162/742: 90130822.parquet
Validating 163/742: 90132865.parquet
Validating 164/742: 90133551.parquet
Validating 165/742: 90134231.parquet
Validating 166/742: 90134236.parquet
Validating 167/742: 90134923.parquet
Validating 168/742: 90137605.parquet
Validating 169/742: 90139722.parquet
Validating 170/742: 90141058.parquet
Validating 171/742: 90141100.parquet
Validating 172/742: 90141770.parquet
Validating 173/742: 90142472.parquet
Validating 174/742: 90143176.parquet
Validating 175/742: 90143864.parquet
Validating 176/742: 90144556.parquet
Validating 177/742: 90145269.parquet
Validating 178/742: 90145960.parquet
Validating 179/742: 90146571.parquet
Validating 180/742: 90146644.parquet
Validating 181/742: 90147327.parquet
Validating 182/742: 90147942.parquet
Validating 183/742: 90147961.parquet
Validating 184/742: 90148025.parquet
Validating 185/742: 90148658.parquet
Validating 186/742: 90148707.parquet
Validating 187/742: 90149323.parquet
Validating 188/742: 90149344.parquet
Validating 189/742: 90150023.parquet
Validating 190/742: 90150049.parquet
Validating 191/742: 90150716.parquet
Validating 192/742: 90150738.parquet
Validating 193/742: 90151402.parquet
Validating 194/742: 90151422.parquet
Validating 195/742: 90152071.parquet
Validating 196/742: 90152097.parquet
Validating 197/742: 90152825.parquet
Validating 198/742: 90153442.parquet
Validating 199/742: 90153469.parquet
Validating 200/742: 90153480.parquet
Validating 201/742: 90153504.parquet
Validating 202/742: 90154127.parquet
Validating 203/742: 90154148.parquet
Validating 204/742: 90154808.parquet
Validating 205/742: 90154835.parquet
Validating 206/742: 90155488.parquet
Validating 207/742: 90155493.parquet
Validating 208/742: 90155518.parquet
Validating 209/742: 90155519.parquet
Validating 210/742: 90156175.parquet
Validating 211/742: 90156178.parquet
Validating 212/742: 90156211.parquet
Validating 213/742: 90156857.parquet
Validating 214/742: 90156866.parquet
Validating 215/742: 90156883.parquet
Validating 216/742: 90156919.parquet
Validating 217/742: 90157554.parquet
Validating 218/742: 90157565.parquet
Validating 219/742: 90157591.parquet
Validating 220/742: 90158257.parquet
Validating 221/742: 90158259.parquet
Validating 222/742: 90158270.parquet
Validating 223/742: 90158292.parquet
Validating 224/742: 90158312.parquet
Validating 225/742: 90158972.parquet
Validating 226/742: 90158973.parquet
Validating 227/742: 90158981.parquet
Validating 228/742: 90159672.parquet
Validating 229/742: 90159674.parquet
Validating 230/742: 90159693.parquet
Validating 231/742: 90160367.parquet
Validating 232/742: 90160373.parquet
Validating 233/742: 90161052.parquet
Validating 234/742: 90161060.parquet
Validating 235/742: 90161683.parquet
Validating 236/742: 90161746.parquet
Validating 237/742: 90162376.parquet
Validating 238/742: 90163074.parquet
Validating 239/742: 90163769.parquet
Validating 240/742: 90164461.parquet
Validating 241/742: 90165148.parquet
Validating 242/742: 90165193.parquet
Validating 243/742: 90165194.parquet
Validating 244/742: 90165858.parquet
Validating 245/742: 90166548.parquet
Validating 246/742: 90167254.parquet
Validating 247/742: 90167953.parquet
Validating 248/742: 90168654.parquet
Validating 249/742: 90169370.parquet
Validating 250/742: 90170085.parquet
Validating 251/742: 90170097.parquet
Validating 252/742: 90170722.parquet
Validating 253/742: 90170793.parquet
Validating 254/742: 90171433.parquet
Validating 255/742: 90171442.parquet
Validating 256/742: 90172140.parquet
Validating 257/742: 90172847.parquet
Validating 258/742: 90172856.parquet
Validating 259/742: 90173560.parquet
Validating 260/742: 90173577.parquet
Validating 261/742: 90173578.parquet
Validating 262/742: 90174249.parquet
Validating 263/742: 90174276.parquet
Validating 264/742: 90175032.parquet
Validating 265/742: 90178520.parquet
Validating 266/742: 90178526.parquet
Validating 267/742: 90179860.parquet
Validating 268/742: 90180558.parquet
Validating 269/742: 90181276.parquet
Validating 270/742: 90181298.parquet
Validating 271/742: 90182006.parquet
Validating 272/742: 90182640.parquet
Validating 273/742: 90182668.parquet
Validating 274/742: 90183389.parquet
Validating 275/742: 90184051.parquet
Validating 276/742: 90184095.parquet
Validating 277/742: 90184098.parquet
Validating 278/742: 90184765.parquet
Validating 279/742: 90184806.parquet
Validating 280/742: 90185459.parquet
Validating 281/742: 90185504.parquet
Validating 282/742: 90185506.parquet
Validating 283/742: 90186182.parquet
Validating 284/742: 90186209.parquet
Validating 285/742: 90186217.parquet
Validating 286/742: 90186885.parquet
Validating 287/742: 90186923.parquet
Validating 288/742: 90187584.parquet
Validating 289/742: 90188276.parquet
Validating 290/742: 90188298.parquet
Validating 291/742: 90188328.parquet
Validating 292/742: 90188334.parquet
Validating 293/742: 90188991.parquet
Validating 294/742: 90189013.parquet
Validating 295/742: 90189698.parquet
Validating 296/742: 90189728.parquet
Validating 297/742: 90190430.parquet
Validating 298/742: 90190446.parquet
Validating 299/742: 90191165.parquet
Validating 300/742: 90191865.parquet
Validating 301/742: 90192562.parquet
Validating 302/742: 90192566.parquet
Validating 303/742: 90192570.parquet
Validating 304/742: 90193179.parquet
Validating 305/742: 90193249.parquet
Validating 306/742: 90193288.parquet
Validating 307/742: 90193976.parquet
Validating 308/742: 90194686.parquet
Validating 309/742: 90194722.parquet
Validating 310/742: 90195365.parquet
Validating 311/742: 90195407.parquet
Validating 312/742: 90196094.parquet
Validating 313/742: 90196118.parquet
Validating 314/742: 90196844.parquet
Validating 315/742: 90197584.parquet
Validating 316/742: 90198283.parquet
Validating 317/742: 90198309.parquet
Validating 318/742: 90199002.parquet
Validating 319/742: 90199014.parquet
Validating 320/742: 90199038.parquet
Validating 321/742: 90199745.parquet
Validating 322/742: 90200473.parquet
Validating 323/742: 90200474.parquet
Validating 324/742: 90200486.parquet
Validating 325/742: 90201202.parquet
Validating 326/742: 90201203.parquet
Validating 327/742: 90205310.parquet
Validating 328/742: 90206035.parquet
Validating 329/742: 90206772.parquet
Validating 330/742: 90207493.parquet
Validating 331/742: 90208223.parquet
Validating 332/742: 90208944.parquet
Validating 333/742: 90208964.parquet
Validating 334/742: 90209716.parquet
Validating 335/742: 90210407.parquet
Validating 336/742: 90210459.parquet
Validating 337/742: 90210475.parquet
Validating 338/742: 90211148.parquet
Validating 339/742: 90211207.parquet
Validating 340/742: 90211875.parquet
Validating 341/742: 90211931.parquet
Validating 342/742: 90211932.parquet
Validating 343/742: 90212606.parquet
Validating 344/742: 90212622.parquet
Validating 345/742: 90213350.parquet
Validating 346/742: 90213369.parquet
Validating 347/742: 90214096.parquet
Validating 348/742: 90214112.parquet
Validating 349/742: 90214152.parquet
Validating 350/742: 90214160.parquet
Validating 351/742: 90214829.parquet
Validating 352/742: 90214841.parquet
Validating 353/742: 90215568.parquet
Validating 354/742: 90215583.parquet
Validating 355/742: 90215588.parquet
Validating 356/742: 90216317.parquet
Validating 357/742: 90216325.parquet
Validating 358/742: 90216337.parquet
Validating 359/742: 90217017.parquet
Validating 360/742: 90217026.parquet
Validating 361/742: 90217042.parquet
Validating 362/742: 90217688.parquet
Validating 363/742: 90217699.parquet
Validating 364/742: 90217713.parquet
Validating 365/742: 90218412.parquet
Validating 366/742: 90218423.parquet
Validating 367/742: 90219144.parquet
Validating 368/742: 90219149.parquet
Validating 369/742: 90219839.parquet
Validating 370/742: 90219883.parquet
Validating 371/742: 90220545.parquet
Validating 372/742: 90220571.parquet
Validating 373/742: 90221261.parquet
Validating 374/742: 90221974.parquet
Validating 375/742: 90221980.parquet
Validating 376/742: 90222014.parquet
Validating 377/742: 90222697.parquet
Validating 378/742: 90222729.parquet
Validating 379/742: 90223426.parquet
Validating 380/742: 90224138.parquet
Validating 381/742: 90224161.parquet
Validating 382/742: 90224829.parquet
Validating 383/742: 90224857.parquet
Validating 384/742: 90224865.parquet
Validating 385/742: 90225559.parquet
Validating 386/742: 90225603.parquet
Validating 387/742: 90226946.parquet
Validating 388/742: 90226992.parquet
Validating 389/742: 90227000.parquet
Validating 390/742: 90227023.parquet
Validating 391/742: 90227027.parquet
Validating 392/742: 90227677.parquet
Validating 393/742: 90227706.parquet
Validating 394/742: 90227713.parquet
Validating 395/742: 90228370.parquet
Validating 396/742: 90228412.parquet
Validating 397/742: 90228424.parquet
Validating 398/742: 90228431.parquet
Validating 399/742: 90228456.parquet
Validating 400/742: 90228460.parquet
Validating 401/742: 90229090.parquet
Validating 402/742: 90229145.parquet
Validating 403/742: 90229153.parquet
Validating 404/742: 90229816.parquet
Validating 405/742: 90229820.parquet
Validating 406/742: 90229871.parquet
Validating 407/742: 90229875.parquet
Validating 408/742: 90230535.parquet
Validating 409/742: 90230582.parquet
Validating 410/742: 90231260.parquet
Validating 411/742: 90231306.parquet
Validating 412/742: 90231957.parquet
Validating 413/742: 90231961.parquet
Validating 414/742: 90232683.parquet
Validating 415/742: 90232731.parquet
Validating 416/742: 90232735.parquet
Validating 417/742: 90233408.parquet
Validating 418/742: 90233409.parquet
Validating 419/742: 90233445.parquet
Validating 420/742: 90234091.parquet
Validating 421/742: 90234096.parquet
Validating 422/742: 90234827.parquet
Validating 423/742: 90234836.parquet
Validating 424/742: 90234864.parquet
Validating 425/742: 90235554.parquet
Validating 426/742: 90236276.parquet
Validating 427/742: 90236302.parquet
Validating 428/742: 90236984.parquet
Validating 429/742: 90238409.parquet
Validating 430/742: 90238433.parquet
Validating 431/742: 90239123.parquet
Validating 432/742: 90239821.parquet
Validating 433/742: 90239831.parquet
Validating 434/742: 90240529.parquet
Validating 435/742: 90240543.parquet
Validating 436/742: 90241873.parquet
Validating 437/742: 90241978.parquet
Validating 438/742: 90241988.parquet
Validating 439/742: 90242579.parquet
Validating 440/742: 90242657.parquet
Validating 441/742: 90243288.parquet
Validating 442/742: 90243367.parquet
Validating 443/742: 90243999.parquet
Validating 444/742: 90244085.parquet
Validating 445/742: 90244091.parquet
Validating 446/742: 90244099.parquet
Validating 447/742: 90244110.parquet
Validating 448/742: 90244717.parquet
Validating 449/742: 90245428.parquet
Validating 450/742: 90245429.parquet
Validating 451/742: 90245487.parquet
Validating 452/742: 90245489.parquet
Validating 453/742: 90245509.parquet
Validating 454/742: 90245513.parquet
Validating 455/742: 90246130.parquet
Validating 456/742: 90246133.parquet
Validating 457/742: 90246217.parquet
Validating 458/742: 90246849.parquet
Validating 459/742: 90246896.parquet
Validating 460/742: 90246903.parquet
Validating 461/742: 90246927.parquet
Validating 462/742: 90246948.parquet
Validating 463/742: 90247518.parquet
Validating 464/742: 90247551.parquet
Validating 465/742: 90247614.parquet
Validating 466/742: 90247647.parquet
Validating 467/742: 90248229.parquet
Validating 468/742: 90248255.parquet
Validating 469/742: 90248261.parquet
Validating 470/742: 90248940.parquet
Validating 471/742: 90248957.parquet
Validating 472/742: 90248963.parquet
Validating 473/742: 90249059.parquet
Validating 474/742: 90249063.parquet
Validating 475/742: 90249693.parquet
Validating 476/742: 90249697.parquet
Validating 477/742: 90250386.parquet
Validating 478/742: 90250406.parquet
Validating 479/742: 90250408.parquet
Validating 480/742: 90250447.parquet
Validating 481/742: 90250452.parquet
Validating 482/742: 90250471.parquet
Validating 483/742: 90250478.parquet
Validating 484/742: 90250479.parquet
Validating 485/742: 90251113.parquet
Validating 486/742: 90251127.parquet
Validating 487/742: 90251134.parquet
Validating 488/742: 90251142.parquet
Validating 489/742: 90251207.parquet
Validating 490/742: 90251825.parquet
Validating 491/742: 90251853.parquet
Validating 492/742: 90251858.parquet
Validating 493/742: 90251922.parquet
Validating 494/742: 90252545.parquet
Validating 495/742: 90252559.parquet
Validating 496/742: 90252565.parquet
Validating 497/742: 90252576.parquet
Validating 498/742: 90252636.parquet
Validating 499/742: 90253257.parquet
Validating 500/742: 90253274.parquet
Validating 501/742: 90253285.parquet
Validating 502/742: 90253341.parquet
Validating 503/742: 90253968.parquet
Validating 504/742: 90253986.parquet
Validating 505/742: 90254020.parquet
Validating 506/742: 90254050.parquet
Validating 507/742: 90254684.parquet
Validating 508/742: 90254702.parquet
Validating 509/742: 90254705.parquet
Validating 510/742: 90254720.parquet
Validating 511/742: 90255404.parquet
Validating 512/742: 90255430.parquet
Validating 513/742: 90256132.parquet
Validating 514/742: 90256834.parquet
Validating 515/742: 90256858.parquet
Validating 516/742: 90256883.parquet
Validating 517/742: 90256889.parquet
Validating 518/742: 90257567.parquet
Validating 519/742: 90257614.parquet
Validating 520/742: 90258281.parquet
Validating 521/742: 90258947.parquet
Validating 522/742: 90258999.parquet
Validating 523/742: 90259027.parquet
Validating 524/742: 90259047.parquet
Validating 525/742: 90259656.parquet
Validating 526/742: 90259704.parquet
Validating 527/742: 90260370.parquet
Validating 528/742: 90260417.parquet
Validating 529/742: 90260447.parquet
Validating 530/742: 90260457.parquet
Validating 531/742: 90261091.parquet
Validating 532/742: 90261132.parquet
Validating 533/742: 90261160.parquet
Validating 534/742: 90261185.parquet
Validating 535/742: 90261804.parquet
Validating 536/742: 90262515.parquet
Validating 537/742: 90263191.parquet
Validating 538/742: 90263289.parquet
Validating 539/742: 90263291.parquet
Validating 540/742: 90263313.parquet
Validating 541/742: 90263905.parquet
Validating 542/742: 90263947.parquet

,file,rows,columns,missing_values,duplicate_rows,valid,errors
0,90044961.parquet,1440,64,0,0,True,[]
1,90045719.parquet,1440,64,0,0,True,[]
2,90047087.parquet,1440,64,0,0,True,[]
3,90047777.parquet,1440,64,0,0,True,[]
4,90048477.parquet,1440,64,0,0,True,[]

In [271]:
print("Total files:", len(validation_df))
print("Valid files:", validation_df["valid"].sum())
print("Invalid files:", (~validation_df["valid"]).sum())

Total files: 742
Valid files: 742
Invalid files: 0